# Lists of tasks that will be executed in parallel.
grid_tasks:
  -
    default_configs: configs/cog/cog_mac.yaml   # MAC on CoGenT



grid_settings:
  # Set number of repetitions of each experiments.
  experiment_repetitions: 10
  # Set number of concurrent running experiments (will be limited by the actual number of available CPUs/GPUs).
  max_concurrent_runs: 7
  # Set trainer.
  trainer: mip-online-trainer